# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillshare < Formula
  desc "Share skills across AI CLI tools"
  homepage "https://github.com/runkids/skillshare"
  version "0.20.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runkids/skillshare/releases/download/v0.20.10/skillshare_0.20.10_darwin_amd64.tar.gz"
      sha256 "7a267ae544604d9e1bc76b90859ca9ada43ecc65e6b568c891111d328570c3d8"

      define_method(:install) do
        bin.install "skillshare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runkids/skillshare/releases/download/v0.20.10/skillshare_0.20.10_darwin_arm64.tar.gz"
      sha256 "057fca336abd2920ccd23b35a21fc3940caf7fc3d4ca37cd04237f04a16276cc"

      define_method(:install) do
        bin.install "skillshare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/runkids/skillshare/releases/download/v0.20.10/skillshare_0.20.10_linux_amd64.tar.gz"
      sha256 "ac829f6c4c916187fda44a3594a5580777c6cc304579c59ac753cd1f973f5a2f"
      define_method(:install) do
        bin.install "skillshare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runkids/skillshare/releases/download/v0.20.10/skillshare_0.20.10_linux_arm64.tar.gz"
      sha256 "c1f6ffc1544fc15b85d97b4adfbde143e3c3280fd2ddde69935da34e32e33d35"
      define_method(:install) do
        bin.install "skillshare"
      end
    end
  end

  test do
    system "#{bin}/skillshare", "version"
  end
end
