# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillshare < Formula
  desc "Share skills across AI CLI tools"
  homepage "https://github.com/runkids/skillshare"
  version "0.6.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runkids/skillshare/releases/download/v0.6.28/skillshare_0.6.28_darwin_amd64.tar.gz"
      sha256 "4b81ec0e48155adc0dcbf64b46a48c42cee57d21b7984b2b1e831dc341b79d3b"

      def install
        bin.install "skillshare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runkids/skillshare/releases/download/v0.6.28/skillshare_0.6.28_darwin_arm64.tar.gz"
      sha256 "94bf965a49116174e1ea6641da8a79ac857c142cef959876c859723b663a12cc"

      def install
        bin.install "skillshare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/runkids/skillshare/releases/download/v0.6.28/skillshare_0.6.28_linux_amd64.tar.gz"
      sha256 "9a793c9c869ebc6adc5ff8ac210fe9fb88f2eed692d63e3117abbbe7938ec75e"
      def install
        bin.install "skillshare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runkids/skillshare/releases/download/v0.6.28/skillshare_0.6.28_linux_arm64.tar.gz"
      sha256 "3fa96778a86382742f2d63cba0aa92e1b2989701d7618b205d4ec18953c4a63f"
      def install
        bin.install "skillshare"
      end
    end
  end

  test do
    system "#{bin}/skillshare", "version"
  end
end
